export enum NodeActionsEnum {
  ADD_NODE = "ADD_NODE",
  UPDATE_NEWLY_ADDED_NODE = "UPDATE_NEWLY_ADDED_NODE"
}

export enum CurrentActionsEnum {
  ADD_CHILD_TO_CURRENT = "ADD_CHILD_TO_CURRENT",
  CHANGE_CURRENT = "CHANGE_CURRENT"
}
